version: "3.7"

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27027:27017"  # Expose MongoDB default port for connection
    volumes:
      - mongodb1_data:/data/db  # Mount volume for MongoDB data persistence
    command: mongod --replSet myReplicaSet  # Specify replica set name

  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27028:27017"  # Expose MongoDB default port for connection
    volumes:
      - mongodb2_data:/data/db  # Mount volume for MongoDB data persistence
    command: mongod --replSet myReplicaSet  # Specify replica set name

volumes:
  mongodb1_data:  # Define volume for MongoDB data persistence
  mongodb2_data:  # Define volume for MongoDB data persistence

networks:
  mongo-cluster:
    driver: bridge